import { Tab } from '@headlessui/react';
import Head from 'next/head';
import Link from 'next/link';

export default function Home() {
  const tabs = [
    {
      key: 'all',
      display: 'All',
    },
    {
      key: 'oceans',
      display: 'Display',
    },
    {
      key: 'forests',
      display: 'Forests',
    },
  ];

  return (
    <div className='h-full  bg-[url("/photography-bg.jpg")] bg-top bg-cover flex flex-col'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <header className='flex justify-between items-center h-[90px] px-6'>
        <div className=''>Photography Portfolio</div>
        <Link
          href='#'
          className='rounded-3xl bg-white text-stone-800 px-3 py-2 hover:bg-opacity-90 font-semibold '
        >
          Get in touch
        </Link>
      </header>
      <main className='grow'>
        <div className='flex flex-col items-center h-full'>
          <Tab.Group>
            <Tab.List className='flex items-center gap-12'>
              {tabs.map((tab) => (
                <Tab key={tab.key}>
                  {({ selected }) => (
                    <span
                      className={selected ? 'text-white' : 'text-stone-500'}
                    >
                      {tab.display}
                    </span>
                  )}
                </Tab>
              ))}
            </Tab.List>
            <Tab.Panels className='bg-stone-900 bg-opacity-75 h-full max-w-[900px] w-full p-2 sm:p-4 my-6'>
              <Tab.Panel>All Photos</Tab.Panel>
              <Tab.Panel>Oceans</Tab.Panel>
              <Tab.Panel>Forests</Tab.Panel>
            </Tab.Panels>
          </Tab.Group>
        </div>
      </main>
      <footer className='h-[60px] flex justify-center'>
        Photography Portfolio
      </footer>
    </div>
  );
}
