import { Tab } from '@headlessui/react';
import Head from 'next/head';
import Link from 'next/link';
import Masonry from 'react-masonry-css';
import classNames from 'classnames';

import ocean1 from '../public/ocean1.jpg';
import ocean2 from '../public/ocean2.jpg';
import ocean3 from '../public/ocean3.jpg';
import ocean4 from '../public/ocean4.jpg';
import ocean5 from '../public/ocean5.jpg';
import Image from 'next/image';

export default function Home() {
  const tabs = [
    {
      key: 'all',
      display: 'All',
    },
    {
      key: 'oceans',
      display: 'Oceans',
    },
    {
      key: 'forests',
      display: 'Forests',
    },
  ];

  return (
    <div className='h-full bg-[url("/photography-bg.jpg")] bg-top bg-cover overflow-auto p-4'>
      <Head>
        <title>Photography Portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <header className='flex justify-between items-center h-[90px] px-10  fixed w-full z-10 top-0'>
        <span className='uppercase text-xl font-semibold'>
          Photography Portfolio
        </span>
        <Link
          href='#'
          className='rounded-3xl bg-white text-stone-800 px-3 py-2 hover:bg-opacity-90 font-semibold '
        >
          Get in touch
        </Link>
      </header>
      <main className='pt-[110px]'>
        <div className='flex flex-col items-center h-full'>
          <Tab.Group>
            <Tab.List className='flex items-center gap-12'>
              {tabs.map((tab) => (
                <Tab key={tab.key} className='p-2'>
                  {({ selected }) => (
                    <span
                      className={classNames(
                        'uppercase font-medium text-lg',
                        selected ? 'text-white' : 'text-stone-500'
                      )}
                    >
                      {tab.display}
                    </span>
                  )}
                </Tab>
              ))}
            </Tab.List>
            <Tab.Panels className='h-full max-w-[900px] w-full my-6'>
              <Tab.Panel className='overflow-auto'>
                <Masonry
                  breakpointCols={2}
                  className='flex gap-2'
                  columnClassName=''
                >
                  <Image src={ocean1} alt={'ocean1'} className='my-4' />
                  <Image src={ocean2} alt={'ocean2'} className='my-4' />
                  <Image src={ocean3} alt={'ocean3'} className='my-4' />
                  <Image src={ocean4} alt={'ocean4'} className='my-4' />
                  <Image src={ocean5} alt={'ocean5'} className='my-4' />

                  {/* <img src='/ocean1.jpg' className='my-2' alt='ocean1' />
                  <img src='/ocean2.jpg' className='my-2' alt='ocean2' />
                  <img src='/ocean3.jpg' className='my-2' alt='ocean3' />
                  <img src='/ocean4.jpg' className='my-2' alt='ocean4' />
                  <img src='/ocean5.jpg' className='my-2' alt='ocean5' /> */}
                </Masonry>
              </Tab.Panel>
              <Tab.Panel>Oceans</Tab.Panel>
              <Tab.Panel>Forests</Tab.Panel>
            </Tab.Panels>
          </Tab.Group>
        </div>
      </main>
      <footer className='h-[90px] uppercase text-lg mt-10 font-medium flex justify-center'>
        Photography Portfolio
      </footer>
    </div>
  );
}
